name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev openjdk-8-jdk zlib1g-dev ccache
        
    - name: Install Buildozer and dependencies
      run: |
        pip install buildozer cython==0.29.33
        
    - name: Discover valid python-for-android tags
      run: |
        # Clonar e descobrir tags disponíveis
        rm -rf .buildozer/android/platform/python-for-android
        git clone https://github.com/kivy/python-for-android.git .buildozer/android/platform/python-for-android
        cd .buildozer/android/platform/python-for-android
        
        # Listar todas tags disponíveis
        echo "📋 TAGS DISPONÍVEIS:"
        git tag -l | head -20
        
        # Usar a branch master (SEMPRE existe)
        git checkout master
        echo "✅ Usando branch master"
        
        cd ../../../../
        
    - name: Build APK with Buildozer
      run: |
        buildozer android update
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: mapa-marianoto-apk
        path: bin/*.apk
        if-no-files-found: error
