name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev openjdk-8-jdk zlib1g-dev ccache
        
    - name: Install Buildozer
      run: |
        pip install buildozer cython==0.29.33
        
    - name: Build APK
      run: |
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: mapa-marianoto-apk
        path: bin/*.apk
        if-no-files-found: error
