name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev openjdk-8-jdk zlib1g-dev ccache unzip
        
    - name: Install Buildozer
      run: |
        pip install buildozer cython==0.29.33
        
    - name: Install Android SDK manually
      run: |
        # Download e instalação MANUAL do Android SDK (CORRIGIDO)
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip -d android-sdk-cmdline
        mkdir -p android-sdk
        mv android-sdk-cmdline/cmdline-tools android-sdk/
        mkdir -p android-sdk/cmdline-tools/latest
        mv android-sdk/cmdline-tools/* android-sdk/cmdline-tools/latest/
        
        # Configurar variáveis de ambiente
        echo "ANDROID_HOME=$GITHUB_WORKSPACE/android-sdk" >> $GITHUB_ENV
        echo "PATH=$GITHUB_WORKSPACE/android-sdk/cmdline-tools/latest/bin:$GITHUB_WORKSPACE/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
        
    - name: Install Android packages
      run: |
        # Aceitar licenças e instalar pacotes necessários
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34" "cmdline-tools;latest"
        
    - name: Build with Buildozer
      run: |
        # Configurar Buildozer para usar o SDK manual
        echo "android.sdk_path = $ANDROID_HOME" >> buildozer.spec
        buildozer android clean
        buildozer android update
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: mapa-marianoto-apk
        path: bin/*.apk
        if-no-files-found: error
