name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev openjdk-8-jdk zlib1g-dev ccache libffi-dev libssl-dev autoconf automake libtool
        
    - name: Install Buildozer and dependencies
      run: |
        pip install buildozer cython==0.29.33 virtualenv
        
    - name: Setup Android environment
      run: |
        # Configurar ambiente Android que o Buildozer espera
        mkdir -p ~/.buildozer/android/platform
        echo "sdk.dir=$HOME/.buildozer/android/platform/android-sdk" > local.properties
        echo "ndk.dir=$HOME/.buildozer/android/platform/android-ndk" >> local.properties
        
    - name: Manual python-for-android setup
      run: |
        # Download MANUAL e completo do python-for-android
        rm -rf .buildozer/android/platform/python-for-android
        git clone https://github.com/kivy/python-for-android.git .buildozer/android/platform/python-for-android
        cd .buildozer/android/platform/python-for-android
        git checkout 2023.08.04 # Versão estável específica
        cd ../../../../
        
    - name: Build APK with verbose logging
      run: |
        # Build com logging detalhado para debug
        buildozer android clean 2>&1 | tee build.log
        buildozer android update 2>&1 | tee -a build.log
        buildozer android debug 2>&1 | tee -a build.log
        
    - name: Check if APK was created
      run: |
        if [ -f bin/*.apk ]; then
          echo "✅ APK criado com sucesso!"
          ls -la bin/
        else
          echo "❌ Falha na criação do APK"
          cat build.log | tail -50
          exit 1
        fi
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: mapa-marianoto-apk
        path: bin/*.apk
        if-no-files-found: error
        
    - name: Upload build log
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: build.log
