name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev openjdk-8-jdk zlib1g-dev ccache
        
    - name: Install Buildozer
      run: |
        pip install buildozer cython==0.29.33
        
    - name: Setup Android SDK (Método Simplificado)
      run: |
        # Configurar variáveis do Android SDK que o Buildozer precisa
        mkdir -p ~/.buildozer/android/platform/android-sdk
        echo "export ANDROID_SDK_ROOT=~/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
        echo "sdk.dir=$HOME/.buildozer/android/platform/android-sdk" > local.properties
        
    - name: Build APK with Buildozer
      run: |
        # Forçar o Buildozer a baixar o Android SDK automaticamente
        buildozer android clean
        buildozer android update
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: mapa-marianoto-apk
        path: bin/*.apk
        if-no-files-found: error
