name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev openjdk-8-jdk zlib1g-dev ccache unzip
        
    - name: Install Buildozer
      run: |
        pip install buildozer cython==0.29.33
        
    - name: Install Android SDK and AIDL
      run: |
        # Instalar Android SDK com os nomes EXATOS
        sudo apt-get install -y google-android-platform-34-installer google-android-build-tools-34.0.0-installer
        
        # Configurar variáveis de ambiente
        echo "ANDROID_HOME=/usr/lib/android-sdk" >> $GITHUB_ENV
        echo "PATH=/usr/lib/android-sdk/platform-tools:/usr/lib/android-sdk/build-tools/34.0.0:$PATH" >> $GITHUB_ENV
        echo "sdk.dir=/usr/lib/android-sdk" > local.properties
        
    - name: Download python-for-android manually
      run: |
        # Download MANUAL do python-for-android
        rm -rf .buildozer
        mkdir -p .buildozer/android/platform
        git clone https://github.com/kivy/python-for-android.git .buildozer/android/platform/python-for-android
        cd .buildozer/android/platform/python-for-android
        git checkout master  # Usar branch master que sempre existe
        cd ../../../../
        
    - name: Build with Buildozer
      run: |
        buildozer android clean
        buildozer android update
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: mapa-marianoto-apk
        path: bin/*.apk
        if-no-files-found: error
        
