name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build APK
      uses: ArturMoskvyak/buildozer-action@v1
      with:
        workdir: .
        
